In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

In [3]:
import sys
sys.version

'3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]'

# Creating arrays using Numpy

In [4]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
# creating arr using numpy
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
# numpy functions.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
# first argument should be less than 2nd
np.arange(20, 10)

array([], dtype=int32)

In [16]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
ar = np.arange(-30, 10)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [19]:
np.arange(10, 10)

array([], dtype=int32)

In [20]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.arange(0, 16, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [22]:
np.zeros(5) # parameter tuning, default float

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(6, dtype = int)

array([0, 0, 0, 0, 0, 0])

In [24]:
np.zeros((2,2), dtype = int) # 2D array with int

array([[0, 0],
       [0, 0]])

In [25]:
np.zeros((2,2), dtype = float) # 2D array with float

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
zero = np.zeros([2, 2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [28]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
n = (6, 7)
n1 = (6, 8)
print(np.zeros(n1, dtype = int))
print()
print(np.zeros(n, dtype = int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [30]:
# ones function.
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [32]:
print(np.ones(n, dtype = int))
print()
print(np.ones(n))

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [33]:
r = range(5)
r

range(0, 5)

In [34]:
for i in r:
    print(i)

0
1
2
3
4


In [35]:
import random
random.rand(2,3)

AttributeError: module 'random' has no attribute 'rand'

In [36]:
np.random.rand(5)

array([0.61213934, 0.08070786, 0.28832525, 0.08674509, 0.07093196])

In [37]:
np.random.rand(2,4) # 2 rows and 4 columns create arrays with random values

array([[0.88412462, 0.17644176, 0.67628007, 0.7110135 ],
       [0.45061021, 0.48763118, 0.20592578, 0.30386873]])

In [38]:
np.random.randint(2,4) # generates int values.

2

In [39]:
np.random.randint(2, 20)

15

In [40]:
np.random.randint(10,40,(10,10)) # Create 10 X 10 matrix, values b/w 10 and 40

array([[19, 17, 38, 24, 22, 36, 33, 12, 38, 39],
       [21, 18, 12, 34, 12, 12, 33, 21, 21, 28],
       [11, 12, 24, 11, 16, 31, 24, 20, 22, 26],
       [35, 16, 35, 39, 30, 18, 38, 36, 22, 25],
       [27, 18, 14, 15, 16, 32, 30, 29, 14, 39],
       [35, 17, 25, 21, 36, 19, 10, 31, 10, 22],
       [24, 29, 36, 15, 12, 39, 32, 25, 38, 26],
       [11, 15, 36, 26, 30, 34, 10, 35, 22, 23],
       [17, 31, 11, 34, 29, 22, 33, 35, 34, 27],
       [19, 32, 13, 14, 14, 23, 25, 15, 31, 19]])

In [42]:
b = np.random.randint(10,20,(5, 4))
b

array([[12, 13, 10, 16],
       [12, 18, 19, 18],
       [15, 12, 10, 14],
       [15, 13, 17, 14],
       [15, 13, 19, 12]])

In [43]:
b[:]

array([[12, 13, 10, 16],
       [12, 18, 19, 18],
       [15, 12, 10, 14],
       [15, 13, 17, 14],
       [15, 13, 19, 12]])

In [44]:
b[1:3] # only rows will be shown

array([[12, 18, 19, 18],
       [15, 12, 10, 14]])

In [45]:
b[1,3] # gives specific elements

18

In [46]:
b[0:-1]

array([[12, 13, 10, 16],
       [12, 18, 19, 18],
       [15, 12, 10, 14],
       [15, 13, 17, 14]])

In [47]:
b[0:-2]

array([[12, 13, 10, 16],
       [12, 18, 19, 18],
       [15, 12, 10, 14]])

In [48]:
b

array([[12, 13, 10, 16],
       [12, 18, 19, 18],
       [15, 12, 10, 14],
       [15, 13, 17, 14],
       [15, 13, 19, 12]])

In [49]:
b[-5,-3]

13

In [50]:
b[-4,2]

19

# operations

In [53]:
arr12 = np.random.randint(1, 100, (10, 10))
arr12

array([[58, 68, 49, 21, 59, 87, 98, 43, 64, 66],
       [ 7, 24, 44, 31, 61,  1, 56, 32, 84,  3],
       [ 2, 90, 56, 69, 89, 81, 41, 17, 69, 49],
       [96,  8, 72, 72, 90, 70,  6, 11, 82, 49],
       [79, 73, 96, 81, 33,  4, 86, 74, 64, 48],
       [98, 74, 62,  8, 96, 29, 35,  4, 76, 20],
       [13,  7, 39, 50, 19, 95, 55, 27, 64, 59],
       [80, 35, 29, 48,  5, 85,  5, 83,  6, 67],
       [51, 10, 99, 42, 79,  6, 33, 66, 12, 65],
       [26, 65, 41, 28, 22, 84, 75, 46, 52, 38]])

In [54]:
arr12[::-1]

array([[26, 65, 41, 28, 22, 84, 75, 46, 52, 38],
       [51, 10, 99, 42, 79,  6, 33, 66, 12, 65],
       [80, 35, 29, 48,  5, 85,  5, 83,  6, 67],
       [13,  7, 39, 50, 19, 95, 55, 27, 64, 59],
       [98, 74, 62,  8, 96, 29, 35,  4, 76, 20],
       [79, 73, 96, 81, 33,  4, 86, 74, 64, 48],
       [96,  8, 72, 72, 90, 70,  6, 11, 82, 49],
       [ 2, 90, 56, 69, 89, 81, 41, 17, 69, 49],
       [ 7, 24, 44, 31, 61,  1, 56, 32, 84,  3],
       [58, 68, 49, 21, 59, 87, 98, 43, 64, 66]])

In [55]:
arr12[::-2]

array([[26, 65, 41, 28, 22, 84, 75, 46, 52, 38],
       [80, 35, 29, 48,  5, 85,  5, 83,  6, 67],
       [98, 74, 62,  8, 96, 29, 35,  4, 76, 20],
       [96,  8, 72, 72, 90, 70,  6, 11, 82, 49],
       [ 7, 24, 44, 31, 61,  1, 56, 32, 84,  3]])

In [56]:
arr

array([0, 1, 2, 3, 4, 5])

In [57]:
arr.reshape(3,2) # convert arr into a matrix of 3 rows and 2 columns

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])